#!/usr/bin/env bash

set -euo pipefail

CONTENT_DIR="content"
SCRIPTS_DIR="scripts"
UPDATE_STAMP="$(date)"

if [ ! -d "$CONTENT_DIR" ]; then
    echo "Content dir: '"$CONTENT_DIR"' not found"
    exit 1
fi

if [ ! -d "$SCRIPTS_DIR" ]; then
    echo "Content dir: '"$CONTENT_DIR"' not found"
    exit 1
fi

# Create main pages
for file in $(find "$CONTENT_DIR/main" -type f); do
    "$SCRIPTS_DIR/templatecontent" \
        -vcontent="$file" \
        templates/site-template.html \
    | sed -e"s|<\!-- NOW -->|$UPDATE_STAMP|" \
    > $(basename $file)
done

# Create recipe pages
for file in $(find "$CONTENT_DIR/recipes" -type f); do
    "$SCRIPTS_DIR/templatecontent" \
        -vcontent=<("$SCRIPTS_DIR/recipe2html" "$file") \
        templates/site-template.html \
    | sed -e's|href="|href="../|' -e"s|<\!-- NOW -->|$UPDATE_STAMP|" \
    > recipes/$(basename $file .recipe).html
done
